language: python
python:
- '2.7'

install:
- pip install -r requirements.txt

script:
- flake8

before_deploy:
- make

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: script.service.torrserver-${TRAVIS_TAG:1}.zip
  skip_cleanup: true
  overwrite: true
  on:
    repo: Nemiroff/script.service.torrserver
    tags: true
